version: '3.8'

services:

  test:
    container_name: projects-ia-house-price-prediction-test
    build: .
    command: test
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: host

  web:
    container_name: projects-ia-house-price-prediction
    build: .
    command: runserver
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: host
